# Generated by Django 5.2.8 on 2026-04-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("doctor", "医生"), ("patient", "病人"), ("family", "家属")],
                default="patient",
                max_length=10,
                verbose_name="用户类型",
            ),
        ),
    ]
