# Generated by Django 4.2.7 on 2025-10-28 07:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.CharField(max_length=50, unique=True)),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('symptoms', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CTScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_image', models.ImageField(upload_to='ct_scans/original/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='ct_scans/processed/')),
                ('scan_mode', models.CharField(default='1', max_length=20)),
                ('tumor_detected', models.BooleanField(default=False)),
                ('tumor_type', models.CharField(blank=True, choices=[('benign', '良性'), ('malignant', '恶性'), ('unknown', '未知')], max_length=20)),
                ('tumor_size', models.CharField(blank=True, max_length=100)),
                ('tumor_location', models.CharField(blank=True, max_length=200)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('ai_analysis', models.TextField(blank=True)),
                ('doctor_review', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct_scans', to='medical_records.medicalrecord')),
            ],
        ),
    ]
