# Generated by Django 4.2.7 on 2025-10-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='bed_num',
            field=models.CharField(blank=True, max_length=50, verbose_name='床号'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='check_project',
            field=models.CharField(blank=True, max_length=200, verbose_name='检查项目'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='科室'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='position',
            field=models.CharField(blank=True, max_length=200, verbose_name='检查部位'),
        ),
    ]
