# Generated by Django 4.2.7 on 2025-10-29 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('medical_records', '0002_medicalrecord_bed_num_medicalrecord_check_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='doctors.doctor'),
        ),
    ]
