# Generated by Django 4.2.7 on 2025-10-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('report_shared', '报告分享'), ('system', '系统通知'), ('reminder', '提醒通知'), ('chat', '聊天消息'), ('message', '消息')], default='system', max_length=20, verbose_name='通知类型'),
        ),
    ]
