# Generated by Django 4.2.7 on 2026-04-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('report_shared', '报告分享'), ('system', '系统通知'), ('reminder', '提醒通知'), ('chat', '聊天消息'), ('message', '消息'), ('appointment', '挂号通知')], default='system', max_length=20, verbose_name='通知类型'),
        ),
    ]
