# Generated by Django 4.2.7 on 2026-04-28 02:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_sync_registered_doctors'),
        ('patients', '0001_initial'),
        ('medical_records', '0003_alter_medicalrecord_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('outpatient', '普通门诊'), ('expert', '专家门诊'), ('emergency', '急诊'), ('followup', '复诊')], default='outpatient', max_length=20)),
                ('visit_date', models.DateTimeField()),
                ('department', models.CharField(blank=True, max_length=100)),
                ('symptoms', models.TextField(blank=True)),
                ('medical_history', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '待接诊'), ('accepted', '已接诊'), ('rejected', '已拒绝'), ('cancelled', '已取消'), ('completed', '已完成')], default='pending', max_length=20)),
                ('reject_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor')),
                ('medical_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='medical_records.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='appointment_patient_44acdc_idx'), models.Index(fields=['doctor', 'status'], name='appointment_doctor__0653d1_idx'), models.Index(fields=['visit_date'], name='appointment_visit_d_30beac_idx')],
            },
        ),
    ]
